name: weldx
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools_scm
  - pip
  # Notebook + Plotting
  - jupyterlab=4.*
  - ipykernel
  - matplotlib=3.7.2
  - ipympl=0.9.3
  - k3d=2.16.1
  # pinned asdf & weldx versions
  - asdf=3.*
  - weldx=0.7.1
  - weldx_widgets=0.2.6
